table bank_rate_monthly_clean
	lineageTag: 4186807c-c1b2-439c-be4d-1464f45b796a

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d3978a6b-793d-4824-9b5d-1f1c74b46cc1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Bank_Rate_Pct
		dataType: double
		lineageTag: 01e1fce1-41fb-4132-bf28-091d907041d4
		summarizeBy: sum
		sourceColumn: Bank_Rate_Pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition bank_rate_monthly_clean = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\mahan\BoE dashboard\Raw_Data\bank_rate_monthly_clean.csv"), [Delimiter = ",", Columns = 2, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Date", type date}, {"Bank_Rate_Pct", type number}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

